### ISSUE TITLE
Module dont show up

### ISSUE THREAD

**Issue by cRPrimo** [marcomerens/anniversarymodule#1]
Hey,
after I inserted and configured the module, it doesn't show up on the MM screen. Is there anything else to consider?
BR

**Comment by marcomerens** [comment]
I would need to see what you put into the config file. Follow the exact format. Like for dates and such.

**Comment by cRPrimo** [comment]
I've managed to make the module appear now, only now I'm wondering how to add more people to the list. I have tried it with:

	defaults: {
		limit:4,
		people:[{name:"Marco",birthdate:"1973-12-30"}]
		people:[{name:"David",birthdate:"2001-05-06"}]
	},

**Comment by marcomerens** [comment]
I recommend @cRPrimo you [learn a bit about JSON](https://www.w3schools.com/js/js_json_intro.asp) 😉 
`defaults` is a JSON objects.
Inside you have properties, they have to be unique (you added people twice, thats incorrect). `limit` and `people` are properties.
`people` is a JSON array.
The right notation for your example would be:
```javascript
defaults: {
	limit:4,
	people:[
                {name:"Marco",birthdate:"1973-12-30"},
	        {name:"David",birthdate:"2001-05-06"}
        ]
},
```

**Comment by mrfoxie** [comment]
![image](https://user-images.githubusercontent.com/25217451/161743731-ca055dbb-4ad3-458d-ad77-2235768580ea.png)

I tried to install it but it's not going to show it.
